### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by kon5t** [pgte/skiff#18]
Win7 x64. I run skiff in three  consoles with different ip ports and databases (2 processes with `standby: true`). At various times, I get the following message in different consoles:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added.
Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:160:15)
    at EventEmitter.once (events.js:185:8)
    at Connection._onceConnected (d:\work\node_modules\skiff\node_modules\skiff-tcp-msgpack\lib\connection.js:52:15)
    at Connection._send (d:\work\node_modules\skiff\node_modules\skiff-tcp-msgpack\lib\connection.js:157:8)
    at Connection.send (d:\work\node_modules\skiff\node_modules\skiff-tcp-msgpack\node_modules\abstract-skiff-transport\lib\connection.js:26:8)
    at Peer._invoke (d:\work\node_modules\skiff\node_modules\skiff-algorithm\lib\peer.js:139:21)
    at invoke (d:\work\node_modules\skiff\node_modules\skiff-algorithm\lib\peer.js:44:18)
    at Object.q.process (d:\work\node_modules\skiff\node_modules\async\lib\async.js:809:21)
    at next (d:\work\node_modules\skiff\node_modules\async\lib\async.js:806:27)
    at d:\work\node_modules\skiff\node_modules\async\lib\async.js:32:16
```

**Comment by pgte** [comment]
Yes, there's this pattern of connection reuse that I think is problematic. See #24.
